spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user-app
    username: us3r
    password: p455w0rd
  jpa:
    hibernate:
      ddl-auto: update

feign:
  client:
    config:
      default:
        loggerLevel: FULL

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
    com.company.user.client.AgifyClient: DEBUG
    org.springframework.web.servlet.mvc.method.annotation.RequestResponseBodyMethodProcessor: TRACE
    org.hibernate.SQL: DEBUG